### ISSUE TITLE
I am confused

### ISSUE THREAD

**Issue by LLuckers** [cheepinator/waecm#1]
Hi guys,

sorry, but i am confused?!

I thought i was working on an secrete project called stodtradl, but now this???

WTF, is wrong with you?

please inserte a description of the repository with the title "Stodtradl".

Thanks!

chears,
Lukas

**Comment by edamike** [comment]
Hi Lukas,

"stodtradl" is not dead. stodtradl will be the biggest success story in history.

👍

**Comment by cheepinator** [comment]
this will not be fixed

**Comment by LLuckers** [comment]
uh, the last time i was put-down that hard was last night with your mum 🐙

**Comment by cheepinator** [comment]
Please stay objective
